# Generated by Django 2.2.28 on 2026-07-17 19:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='PDF',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/Users/johnelliottcisneros/Documents/Codex/2026-07-17/i/pda/src/media'), upload_to='pdfs/'),
        ),
    ]
