# Generated by Django 2.2.28 on 2026-08-08 15:22

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260717_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDF', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/Users/johnelliottcisneros/Documents/Codex/2026-07-17/i/pda/src/media'), upload_to='group_pdfs/')),
                ('accesscode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AccessCode')),
            ],
        ),
        migrations.CreateModel(
            name='CoreGroupuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesscode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AccessCode')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
    ]
