class DC():
    AGE_CHOICES = (
        ("Under-17", "Under-17"),
        ("18-24", "18-24"),
        ("25-34", "25-34"),
        ("35-44", "35-44"),
        ("45-54", "45-54"),
        ("55-64", "55-64"),
        ("65-75", "65-75"),
        ("Over-75", "Over-75"),
        ("Other", "Other")
    )

    RELIGION_CHOICES = (
        ("African traditional religion", "African traditional religion"),
        ("Bahá'í", "Bahá'í"),
        ("Buddhism", "Buddhism"),
        ("Chinese traditional religion", "Chinese traditional religion"),
        ("Christianity", "Christianity"),
        ("Hinduism", "Hinduism"),
        ("Islam", "Islam"),
        ("Jainism", "Jainism"),
        ("Judaism", "Judaism"),
        ("Secular/non-religious/agnostic/atheist", "Secular/non-religious/agnostic/atheist"),
        ("Shinto", "Shinto"),
        ("Sikhism", "Sikhism"),
        ("Spiritism", "Spiritism"),
        ("Spiritual but not religious", "Spiritual but not religious"),
        ("Other", "Other")
    )

    AREA_CHOICES = (
        ("Urban", "Urban"),
        ("Suburban", "Suburban"),
        ("Rural", "Rural"),
        ("Other", "Other")
    )

    DISABILITY_CHOICES = (
        ("Able-bodied", "Able-bodied"),
        ("Disabled", "Disabled")
    )

    ECONOMIC_CHOICES = (
        ("Bottom 10%", "Bottom 10%"),
        ("Bottom 25%", "Bottom 25%"),
        ("Middle 30%", "Middle 30%"),
        ("Top 25%", "Top 25%"),
        ("Top 10%", "Top 10%"),
        ("Other", "Other")
    )

    EMPLOYMENT_CHOICES = (
        ("Employed for wages", "Employed for wages"),
        ("Self-employed", "Self-employed"),
        ("Out of work and looking for work", "Out of work and looking for work"),
        ("Out of work but not currently looking for work", "Out of work but not currently looking for work"),
        ("A homemaker", "A homemaker"),
        ("A student", "A student"),
        ("Military", "Military"),
        ("Retired", "Retired"),
        ("Unable to work", "Unable to work"),
        ("Other", "Other")
    )

    EDUCATION_CHOICES = (
        ("none", "none"),
        ("8th grade", "8th grade"),
        ("High school graduate, diploma or the equivalent (for example: GED)",
         "High school graduate, diploma or the equivalent (for example: GED)"),
        ("Trade/technical/vocational training", "Trade/technical/vocational training"),
        ("Associate degree", "Associate degree"),
        ("Some college", "Some college"),
        ("Bachelor’s degree", "Bachelor’s degree"),
        ("Master’s degree", "Master’s degree"),
        ("Professional degree", "Professional degree"),
        ("Doctorate degree", "Doctorate degree"),
        ("Other", "Other")
    )

    MARITAL_CHOICES = (
        ("Single", "Single"),
        ("Married or domestic partnership", "Married or domestic partnership"),
        ("Widowed", "Widowed"),
        ("Divorced", "Divorced"),
        ("Separated", "Separated"),
        ("Not married but in a committed long term relationship.",
         "Not married but in a committed long term relationship."),
        ("Other", "Other")
    )

    RACE_CULTURE_CHOICES = (
        ("I do not live in the United States", "I do not live in the United States"),
        ("Non-Hispanic White or Euro-American", "Non-Hispanic White or Euro-American"),
        ("Black, Afro-Caribbean, or African American", "Black, Afro-Caribbean, orAfrican American"),
        ("Latino or Hispanic American", "Latino or Hispanic American"),
        ("East Asian or Asian American", "East Asian or Asian American"),
        ("South Asian or Indian American", "South Asian or Indian American"),
        ("Middle Eastern or Arab American", "Middle Eastern or Arab American"),
        ("Native American or Alaskan Native", "Native American or Alaskan Native"),
        ("Other", "Other")
    )

    PERCEPTION_CHOICES = (
        ("As a White Person", "As a White Person"),
        ("As a Person of Color", "As a Person of Color")
    )

    SEXUAL_ORIENTATION_CHOICES = (
        ("LGBTQ+", "LGBTQ+"),
        ("Straight", "Straight")
    )

    GENDER_CHOICES = (
        ("Female", "Female"),
        ("Genderqueer/Androgynous", "Genderqueer/Androgynous"),
        ("Intersex", "Intersex"),
        ("Male", "Male"),
        ("Transgender: FTM (female-to-male)", "Transgender: FTM (female-to-male)"),
        ("Transgender: MTF (male-to-female)", "Transgender: MTF (male-to-female)"),
        ("Other", "Other")
    )

    COB_CHOICES = (
        ("  0. US - United States", "  0. US - United States"),
        ("  1. AD - Andorra", "  1. AD - Andorra"),
        ("  2. AE - United Arab Emirates", "  2. AE - United Arab Emirates"),
        ("  3. AF - Afghanistan", "  3. AF - Afghanistan"),
        ("  4. AG - Antigua and Barbuda", "  4. AG - Antigua and Barbuda"),
        ("  5. AI - Anguilla", "  5. AI - Anguilla"),
        ("  6. AL - Albania", "  6. AL - Albania"),
        ("  7. AM - Armenia", "  7. AM - Armenia"),
        ("  8. AO - Angola", "  8. AO - Angola"),
        ("  9. AQ - Antarctica", "  9. AQ - Antarctica"),
        (" 10. AR - Argentina", " 10. AR - Argentina"),
        (" 12. AT - Austria", " 12. AT - Austria"),
        (" 13. AU - Australia", " 13. AU - Australia"),
        (" 14. AW - Aruba", " 14. AW - Aruba"),
        (" 15. AZ - Azerbaijan", " 15. AZ - Azerbaijan"),
        (" 16. BA - Bosnia and Herzegovina", " 16. BA - Bosnia and Herzegovina"),
        (" 17. BB - Barbados", " 17. BB - Barbados"),
        (" 18. BD - Bangladesh", " 18. BD - Bangladesh"),
        (" 19. BE - Belgium", " 19. BE - Belgium"),
        (" 20. BF - Burkina Faso", " 20. BF - Burkina Faso"),
        (" 31. BG - Bulgaria", " 31. BG - Bulgaria"),
        (" 32. BH - Bahrain", " 32. BH - Bahrain"),
        (" 33. BI - Burundi", " 33. BI - Burundi"),
        (" 34. BJ - Benin", " 34. BJ - Benin"),
        (" 35. BL - Saint Barthelemy", " 35. BL - Saint Barthelemy"),
        (" 36. BM - Bermuda", " 36. BM - Bermuda"),
        (" 37. BN - Brunei", " 37. BN - Brunei"),
        (" 38. BO - Bolivia", " 38. BO - Bolivia"),
        (" 39. BR - Brazil", " 39. BR - Brazil"),
        (" 40. BS - Bahamas, The", " 40. BS - Bahamas, The"),
        (" 41. BT - Bhutan", " 41. BT - Bhutan"),
        (" 42. BV - Bouvet Island", " 42. BV - Bouvet Island"),
        (" 43. BW - Botswana", " 43. BW - Botswana"),
        (" 44. BY - Belarus", " 44. BY - Belarus"),
        (" 45. BZ - Belize", " 45. BZ - Belize"),
        (" 46. CA - Canada", " 46. CA - Canada"),
        (" 47. CC - Cocos (Keeling) Islands", " 47. CC - Cocos (Keeling) Islands"),
        (" 48. CD - Congo, Democratic Republic of the", " 48. CD - Congo, Democratic Republic of the"),
        (" 49. CF - Central African Republic", " 49. CF - Central African Republic"),
        (" 50. CG - Congo, Republic of the", " 50. CG - Congo, Republic of the"),
        (" 51. CH - Switzerland", " 51. CH - Switzerland"),
        (" 52. CI - Cote d'Ivoire", " 52. CI - Cote d'Ivoire"),
        (" 53. CK - Cook Islands", " 53. CK - Cook Islands"),
        (" 54. CL - Chile", " 54. CL - Chile"),
        (" 55. CM - Cameroon", " 55. CM - Cameroon"),
        (" 56. CN - China", " 56. CN - China"),
        (" 57. CO - Colombia", " 57. CO - Colombia"),
        (" 58. CR - Costa Rica", " 58. CR - Costa Rica"),
        (" 59. CU - Cuba", " 59. CU - Cuba"),
        (" 61. CV - Cape Verde", " 61. CV - Cape Verde"),
        (" 62. CW - Curacao", " 62. CW - Curacao"),
        (" 63. CX - Christmas Island", " 63. CX - Christmas Island"),
        (" 64. CY - Cyprus", " 64. CY - Cyprus"),
        (" 65. CZ - Czech Republic", " 65. CZ - Czech Republic"),
        (" 66. DE - Germany", " 66. DE - Germany"),
        (" 67. DJ - Djibouti", " 67. DJ - Djibouti"),
        (" 68. DK - Denmark", " 68. DK - Denmark"),
        (" 69. DM - Dominica", " 69. DM - Dominica"),
        (" 70. DO - Dominican Republic", " 70. DO - Dominican Republic"),
        (" 71. DZ - Algeria", " 71. DZ - Algeria"),
        (" 72. EC - Ecuador", " 72. EC - Ecuador"),
        (" 73. EE - Estonia", " 73. EE - Estonia"),
        (" 74. EG - Egypt", " 74. EG - Egypt"),
        (" 75. EH - Western Sahara", " 75. EH - Western Sahara"),
        (" 76. ER - Eritrea", " 76. ER - Eritrea"),
        (" 71. ES - Spain", " 71. ES - Spain"),
        (" 77. ET - Ethiopia", " 77. ET - Ethiopia"),
        (" 78. FI - Finland", " 78. FI - Finland"),
        (" 79. FJ - Fiji", " 79. FJ - Fiji"),
        (" 80. FK - Falkland Islands (Islas Malvinas)", " 80. FK - Falkland Islands (Islas Malvinas)"),
        (" 81. FM - Micronesia, Federated States of", " 81. FM - Micronesia, Federated States of"),
        (" 83. FO - Faroe Islands", " 83. FO - Faroe Islands"),
        (" 84. FR - France", " 84. FR - France"),
        (" 85. FX - France, Metropolitan", " 85. FX - France, Metropolitan"),
        (" 86. GA - Gabon", " 86. GA - Gabon"),
        (" 87. GB - United Kingdom", " 87. GB - United Kingdom"),
        (" 88. GD - Grenada", " 88. GD - Grenada"),
        (" 89. GE - Georgia", " 89. GE - Georgia"),
        (" 90. GF - French Guiana", " 90. GF - French Guiana"),
        (" 91. GG - Guernsey", " 91. GG - Guernsey"),
        (" 92. GH - Ghana", " 92. GH - Ghana"),
        (" 93. GI - Gibraltar", " 93. GI - Gibraltar"),
        (" 94. GL - Greenland", " 94. GL - Greenland"),
        (" 95. GM - Gambia, The", " 95. GM - Gambia, The"),
        (" 96. GN - Guinea", " 96. GN - Guinea"),
        (" 97. GP - Guadeloupe", " 97. GP - Guadeloupe"),
        (" 98. GQ - Equatorial Guinea", " 98. GQ - Equatorial Guinea"),
        (" 99. GR - Greece", " 99. GR - Greece"),
        ("101. GS - South Georgia and the Islands", "101. GS - South Georgia and the Islands"),
        ("102. GT - Guatemala", "102. GT - Guatemala"),
        ("103. GU - Guam", "103. GU - Guam"),
        ("104. GW - Guinea-Bissau", "104. GW - Guinea-Bissau"),
        ("105. GY - Guyana", "105. GY - Guyana"),
        ("106. HK - Hong Kong", "106. HK - Hong Kong"),
        ("107. HM - Heard Island and McDonald Islands", "107. HM - Heard Island and McDonald Islands"),
        ("108. HN - Honduras", "108. HN - Honduras"),
        ("109. HR - Croatia", "109. HR - Croatia"),
        ("110. HT - Haiti", "110. HT - Haiti"),
        ("111. HU - Hungary", "111. HU - Hungary"),
        ("112. ID - Indonesia", "112. ID - Indonesia"),
        ("113. IE - Ireland", "113. IE - Ireland"),
        ("114. IL - Israel", "114. IL - Israel"),
        ("115. IM - Isle of Man", "115. IM - Isle of Man"),
        ("116. IN - India", "116. IN - India"),
        ("117. IO - British Indian Ocean Territory", "117. IO - British Indian Ocean Territory"),
        ("118. IQ - Iraq", "118. IQ - Iraq"),
        ("119. IR - Iran", "119. IR - Iran"),
        ("120. IS - Iceland", "120. IS - Iceland"),
        ("121. IT - Italy", "121. IT - Italy"),
        ("122. JE - Jersey", "122. JE - Jersey"),
        ("123. JM - Jamaica", "123. JM - Jamaica"),
        ("124. JO - Jordan", "124. JO - Jordan"),
        ("125. JP - Japan", "125. JP - Japan"),
        ("126. KE - Kenya", "126. KE - Kenya"),
        ("127. KG - Kyrgyzstan", "127. KG - Kyrgyzstan"),
        ("128. KH - Cambodia", "128. KH - Cambodia"),
        ("129. KI - Kiribati", "129. KI - Kiribati"),
        ("130. KM - Comoros", "130. KM - Comoros"),
        ("131. KN - Saint Kitts and Nevis", "131. KN - Saint Kitts and Nevis"),
        ("132. KP - Korea, North", "132. KP - Korea, North"),
        ("133. KR - Korea, South", "133. KR - Korea, South"),
        ("134. KW - Kuwait", "134. KW - Kuwait"),
        ("135. KY - Cayman Islands", "135. KY - Cayman Islands"),
        ("136. KZ - Kazakhstan", "136. KZ - Kazakhstan"),
        ("137. LA - Laos", "137. LA - Laos"),
        ("138. LB - Lebanon", "138. LB - Lebanon"),
        ("139. LC - Saint Lucia", "139. LC - Saint Lucia"),
        ("140. LI - Liechtenstein", "140. LI - Liechtenstein"),
        ("     LK - Sri Lanka", "     LK - Sri Lanka"),
        ("     LR - Liberia", "     LR - Liberia"),
        ("     LS - Lesotho", "     LS - Lesotho"),
        ("     LT - Lithuania", "     LT - Lithuania"),
        ("     LU - Luxembourg", "     LU - Luxembourg"),
        ("     LV - Latvia", "     LV - Latvia"),
        ("     LY - Libya", "     LY - Libya"),
        ("     MA - Morocco", "     MA - Morocco"),
        ("     MC - Monaco", "     MC - Monaco"),
        ("     MD - Moldova", "     MD - Moldova"),
        ("     ME - Montenegro", "     ME - Montenegro"),
        ("     MF - Saint Martin", "     MF - Saint Martin"),
        ("     MG - Madagascar", "     MG - Madagascar"),
        ("     MH - Marshall Islands", "     MH - Marshall Islands"),
        ("     MK - Macedonia", "     MK - Macedonia"),
        ("     ML - Mali", "     ML - Mali"),
        ("     MM - Burma", "     MM - Burma"),
        ("     MN - Mongolia", "     MN - Mongolia"),
        ("     MO - Macau", "     MO - Macau"),
        ("     MP - Northern Mariana Islands", "     MP - Northern Mariana Islands"),
        ("     MQ - Martinique", "     MQ - Martinique"),
        ("     MR - Mauritania", "     MR - Mauritania"),
        ("     MS - Montserrat", "     MS - Montserrat"),
        ("     MT - Malta", "     MT - Malta"),
        ("     MU - Mauritius", "     MU - Mauritius"),
        ("     MV - Maldives", "     MV - Maldives"),
        ("     MW - Malawi", "     MW - Malawi"),
        ("     MX - Mexico", "     MX - Mexico"),
        ("     MY - Malaysia", "     MY - Malaysia"),
        ("     MZ - Mozambique", "     MZ - Mozambique"),
        ("     NA - Namibia", "     NA - Namibia"),
        ("     NC - New Caledonia", "     NC - New Caledonia"),
        ("     NE - Niger", "     NE - Niger"),
        ("     NF - Norfolk Island", "     NF - Norfolk Island"),
        ("     NG - Nigeria", "     NG - Nigeria"),
        ("     NI - Nicaragua", "     NI - Nicaragua"),
        ("     NL - Netherlands", "     NL - Netherlands"),
        ("     NO - Norway", "     NO - Norway"),
        ("     NP - Nepal", "     NP - Nepal"),
        ("     NR - Nauru", "     NR - Nauru"),
        ("     NU - Niue", "     NU - Niue"),
        ("     NZ - New Zealand", "     NZ - New Zealand"),
        ("     OM - Oman", "     OM - Oman"),
        ("     PA - Panama", "     PA - Panama"),
        ("     PE - Peru", "     PE - Peru"),
        ("     PF - French Polynesia", "     PF - French Polynesia"),
        ("     PG - Papua New Guinea", "     PG - Papua New Guinea"),
        ("     PH - Philippines", "     PH - Philippines"),
        ("     PK - Pakistan", "     PK - Pakistan"),
        ("     PL - Poland", "     PL - Poland"),
        ("     PM - Saint Pierre and Miquelon", "     PM - Saint Pierre and Miquelon"),
        ("     PN - Pitcairn Islands", "     PN - Pitcairn Islands"),
        ("     PS - Gaza Strip", "     PS - Gaza Strip"),
        ("     PS - West Bank", "     PS - West Bank"),
        ("     PT - Portugal", "     PT - Portugal"),
        ("     PW - Palau", "     PW - Palau"),
        ("     PY - Paraguay", "     PY - Paraguay"),
        ("     QA - Qatar", "     QA - Qatar"),
        ("     RE - Reunion", "     RE - Reunion"),
        ("     RO - Romania", "     RO - Romania"),
        ("     RS - Serbia", "     RS - Serbia"),
        ("     RU - Russia", "     RU - Russia"),
        ("     RW - Rwanda", "     RW - Rwanda"),
        ("     SA - Saudi Arabia", "     SA - Saudi Arabia"),
        ("     SB - Solomon Islands", "     SB - Solomon Islands"),
        ("     SC - Seychelles", "     SC - Seychelles"),
        ("     SD - Sudan", "     SD - Sudan"),
        ("     SE - Sweden", "     SE - Sweden"),
        ("     SG - Singapore", "     SG - Singapore"),
        ("     SH - Saint Helena, Ascension, and Tristan da Cunha",
         "     SH - Saint Helena, Ascension, and Tristan da Cunha"),
        ("     SI - Slovenia", "     SI - Slovenia"),
        ("     SJ - Svalbard", "     SJ - Svalbard"),
        ("     SK - Slovakia", "     SK - Slovakia"),
        ("     SL - Sierra Leone", "     SL - Sierra Leone"),
        ("     SM - San Marino", "     SM - San Marino"),
        ("     SN - Senegal", "     SN - Senegal"),
        ("     SO - Somalia", "     SO - Somalia"),
        ("     SR - Suriname", "     SR - Suriname"),
        ("     SS - South Sudan", "     SS - South Sudan"),
        ("     ST - Sao Tome and Principe", "     ST - Sao Tome and Principe"),
        ("     SV - El Salvador", "     SV - El Salvador"),
        ("     SX - Sint Maarten", "     SX - Sint Maarten"),
        ("     SY - Syria", "     SY - Syria"),
        ("     SZ - Swaziland", "     SZ - Swaziland"),
        ("     TC - Turks and Caicos Islands", "     TC - Turks and Caicos Islands"),
        ("     TD - Chad", "     TD - Chad"),
        ("     TF - French Southern and Antarctic Lands", "     TF - French Southern and Antarctic Lands"),
        ("     TG - Togo", "     TG - Togo"),
        ("     TH - Thailand", "     TH - Thailand"),
        ("     TJ - Tajikistan", "     TJ - Tajikistan"),
        ("     TK - Tokelau", "     TK - Tokelau"),
        ("     TL - Timor-Leste", "     TL - Timor-Leste"),
        ("     TM - Turkmenistan", "     TM - Turkmenistan"),
        ("     TN - Tunisia", "     TN - Tunisia"),
        ("     TO - Tonga", "     TO - Tonga"),
        ("     TR - Turkey", "     TR - Turkey"),
        ("     TT - Trinidad and Tobago", "     TT - Trinidad and Tobago"),
        ("     TV - Tuvalu", "     TV - Tuvalu"),
        ("     TW - Taiwan", "     TW - Taiwan"),
        ("     TZ - Tanzania", "     TZ - Tanzania"),
        ("     UA - Ukraine", "     UA - Ukraine"),
        ("     UG - Uganda", "     UG - Uganda"),
        ("     UM - United States Minor Outlying Islands", "     UM - United States Minor Outlying Islands"),
        ("     UY - Uruguay", "     UY - Uruguay"),
        ("     UZ - Uzbekistan", "     UZ - Uzbekistan"),
        ("     VA - Holy See (Vatican City)", "     VA - Holy See (Vatican City)"),
        ("     VC - Saint Vincent and the Grenadines", "     VC - Saint Vincent and the Grenadines"),
        ("     VE - Venezuela", "     VE - Venezuela"),
        ("     VG - British Virgin Islands", "     VG - British Virgin Islands"),
        ("     VI - Virgin Islands", "     VI - Virgin Islands"),
        ("     VN - Vietnam", "     VN - Vietnam"),
        ("     VU - Vanuatu", "     VU - Vanuatu"),
        ("     WF - Wallis and Futuna", "     WF - Wallis and Futuna"),
        ("     WS - Samoa", "     WS - Samoa"),
        ("     XK - Kosovo", "     XK - Kosovo"),
        ("     YE - Yemen", "     YE - Yemen"),
        ("     YT - Mayotte", "     YT - Mayotte"),
        ("     ZA - South Africa", "     ZA - South Africa"),
        ("     ZM - Zambia", "     ZM - Zambia"),
        ("     ZW - Zimbabwe", "     ZW - Zimbabwe"),
        ("Other", "Other")
    )

    STATE_CHOICES = (
        ("AL Alabama", "AL Alabama"),
        ("AK Alaska", "AK Alaska"),
        ("AZ Arizona", "AZ Arizona"),
        ("AR Arkansas", "AR Arkansas"),
        ("CA California", "CA California"),
        ("CO Colorado", "CO Colorado"),
        ("CT Connecticut", "CT Connecticut"),
        ("DE Delaware", "DE Delaware"),
        ("DC District of Columbia", "DC District of Columbia"),
        ("FL Florida", "FL Florida"),
        ("GA Georgia", "GA Georgia"),
        ("GU Guam", "GU Guam"),
        ("HI Hawaii", "HI Hawaii"),
        ("ID Idaho", "ID Idaho"),
        ("IL Illinois", "IL Illinois"),
        ("IN Indiana", "IN Indiana"),
        ("IA Iowa", "IA Iowa"),
        ("KS Kansas", "KS Kansas"),
        ("KY Kentucky", "KY Kentucky"),
        ("LA Louisiana", "LA Louisiana"),
        ("ME Maine", "ME Maine"),
        ("MD Maryland", "MD Maryland"),
        ("MA Massachusetts", "MA Massachusetts"),
        ("MI Michigan", "MI Michigan"),
        ("MN Minnesota", "MN Minnesota"),
        ("MS Mississippi", "MS Mississippi"),
        ("MO Missouri", "MO Missouri"),
        ("MT Montana", "MT Montana"),
        ("NE Nebraska", "NE Nebraska"),
        ("NV Nevada", "NV Nevada"),
        ("NH New Hampshire", "NH New Hampshire"),
        ("NJ New Jersey", "NJ New Jersey"),
        ("NM New Mexico", "NM New Mexico"),
        ("NY New York", "NY New York"),
        ("NC North Carolina", "NC North Carolina"),
        ("ND North Dakota", "ND North Dakota"),
        ("OH Ohio", "OH Ohio"),
        ("OK Oklahoma", "OK Oklahoma"),
        ("OR Oregon", "OR Oregon"),
        ("PA Pennsylvania", "PA Pennsylvania"),
        ("PR Puerto Rico", "PR Puerto Rico"),
        ("RI Rhode Island", "RI Rhode Island"),
        ("SC South Carolina", "SC South Carolina"),
        ("SD South Dakota", "SD South Dakota"),
        ("TN Tennessee", "TN Tennessee"),
        ("TX Texas", "TX Texas"),
        ("UT Utah", "UT Utah"),
        ("VI US Virgin Islands", "VI US Virgin Islands"),
        ("VT Vermont", "VT Vermont"),
        ("VA Virginia", "VA Virginia"),
        ("WA Washington", "WA Washington"),
        ("WV West Virginia", "WV West Virginia"),
        ("WI Wisconsin", "WI Wisconsin"),
        ("WY Wyoming", "WY Wyoming"),
        ("Other", "Other")
    )

    PURPOSE_CHOICES = (
        ("00% - 20%", "00% - 20%"),
        ("20% - 40%", "20% - 40%"),
        ("40% - 60%", "40% - 60%"),
        ("60% - 80%", "60% - 80%"),
        ("80% - 100%", "80% - 100%"),
        ("Other", "Other")
    )

    SAFETY_CHOICES = (
        ("when we can deeply listen to, and understand, diverse perspectives",
         "when we can deeply listen to, and understand, diverse perspectives"),
        ("when we stop stereotyping, and treat all people with respect--the way we would like to be treated.",
         "when we stop stereotyping, and treat all people with respect--the way we would like to be treated."),
        (
        "from our willingness to risk and sacrifice everything--to give our life and even our death,to serve and protect our own.",
        "from our willingness to risk and sacrifice everything--to give our life and even our death, to serve and protect our own.")
    )

    GENDER_PERCEPTION_CHOICES = (
        ("as a woman","as a woman"),
        ("as a man","as a man")
    )
