"""
Django settings for TheSum project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
import os

import environ
from django.core.exceptions import ImproperlyConfigured

env = environ.Env()
environ.Env.read_env()


ENV = env('ENV', default='testing')
IS_PRODUCTION = ENV == "PRODUCTION"


def env_bool(name, default=False):
    return env.bool(name, default=default)


def env_list(name, default=None):
    value = env(name, default=None)
    if value is None:
        return default or []
    return [item.strip() for item in value.split(',') if item.strip()]


_missing = object()


def env_first(*names, default=_missing):
    for name in names:
        value = env(name, default=None)
        if value not in (None, ''):
            return value
    if default is not _missing:
        return default
    raise ImproperlyConfigured("Set one of these environment variables: %s" % ", ".join(names))

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if not IS_PRODUCTION:
    SECRET_KEY = '!-!4p2@hx$!o23bm54)!bwh0!8+&i@^%dex8=h8))zg+g*(!gt'
else:
    SECRET_KEY = env('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
if not IS_PRODUCTION:
    DEBUG = True
else:
    DEBUG = False

if IS_PRODUCTION:
    app_url = env('APP_URL')
    ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', default=[app_url, "www."+app_url])
    import requests
    EC2_PRIVATE_IP = None
    try:
        EC2_PRIVATE_IP = requests.get(
            'http://169.254.169.254/latest/meta-data/local-ipv4',
            timeout=0.01).text
    except requests.exceptions.RequestException:
        pass

    if EC2_PRIVATE_IP:
        ALLOWED_HOSTS.append(EC2_PRIVATE_IP)
else:
    ALLOWED_HOSTS = ["128.143.67.97", "127.0.0.1", "127.0.1.1"]

CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')

# Application definition

INSTALLED_APPS = [
    'suit.apps.DjangoSuitConfig',
    'core.apps.CoreConfig',
    'visualization.apps.VisualizationConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'paypal.standard.ipn',
    'paypal.standard.pdt',
    'storages',
    'guardian',
]

MIDDLEWARE = [
    'core.middleware.RequiredDataMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.SessionExpirationMiddleware',
    'core.middleware.PermissionMiddleware',
]

ROOT_URLCONF = 'TheSum.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TheSum.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# Uses either local SQLite, local PostgreSQL, or AWS PostgreSQL.
USE_LOCAL_POSTGRES = env_bool('USE_LOCAL_POSTGRES', default=False)

if IS_PRODUCTION:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env_first('PGDATABASE', 'RDS_DB_NAME'),
            'USER': env_first('PGUSER', 'RDS_USERNAME', 'RDS_USER'),
            'PASSWORD': env_first(
                'PGPASSWORD',
                'RDS_PASSWORD',
                'PRODUCTION_DB_PASSWORD',
            ),
            'HOST': env_first('PGHOST', 'RDS_HOSTNAME', 'RDS_HOST'),
            'PORT': env_first('PGPORT', 'RDS_PORT', default='5432'),
        }
    }
elif USE_LOCAL_POSTGRES:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': env('LOCAL_POSTGRES_DB', default='pda_local'),
            'USER': env('LOCAL_POSTGRES_USER', default=os.getenv('USER', '')),
            'PASSWORD': env('LOCAL_POSTGRES_PASSWORD', default=''),
            'HOST': env('LOCAL_POSTGRES_HOST', default=''),
            'PORT': env('LOCAL_POSTGRES_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

# to hook guardian’s authentication backend
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # this is default
    'guardian.backends.ObjectPermissionBackend',
)

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

EMAIL_BACKEND = env_first(
    'EMAIL_BACKEND',
    'EMAIL_BACKEND_PROD',
    default='django.core.mail.backends.smtp.EmailBackend' if IS_PRODUCTION else 'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = env('EMAIL_HOST', default='localhost')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', default=True)
FROM_EMAIL = env('FROM_EMAIL', default='local@example.com')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default=FROM_EMAIL)
SERVER_EMAIL = env('SERVER_EMAIL', default=FROM_EMAIL)
BCC_EMAIL = env('BCC_EMAIL', default=FROM_EMAIL)
EMAIL_TIMEOUT = env.int('EMAIL_TIMEOUT', default=10)

SEND_PDF_EMAIL = env('SEND_PDF_EMAIL', default='ON')
SCHEDULING_URL = env('SCHEDULING_URL', default='')

if not DEBUG:
    ADMINS = [('error_report', env('ERROR_REPORT_EMAIL'))]


# Paypal SETTINGS
# we will need to change the identity token and email to Elliott's account
if IS_PRODUCTION:
    PAYPAL_TEST = False

    PAYPAL_IDENTITY_TOKEN = env('PAYPAL_IDENTITY_TOKEN')
    PAYPAL_RECEIVER_EMAIL = env_first('PAYPAL_RECEIVER_EMAIL', 'PAYPAL_RECIEVER_EMAIL')
else:
    PAYPAL_TEST = True

    PAYPAL_IDENTITY_TOKEN = "8KqUTP8UCiDAsHh6LeJUsg7D5quIRJu_HvUPa5QtcDNDqy4dCSQaCB8UZ-m"
    PAYPAL_RECEIVER_EMAIL = 'sb-afoqb568566@business.example.com'

# Backward-compatible alias for the legacy misspelled setting used across the app.
PAYPAL_RECIEVER_EMAIL = PAYPAL_RECEIVER_EMAIL

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

if IS_PRODUCTION:
    AWS_ACCESS_KEY_ID = env_first('ACCESS_KEY_ID', 'AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env_first(
        'SECRET_ACCESS_KEY',
        'AWS_SECRET_ACCESS_KEY',
    )
    AWS_STORAGE_BUCKET_NAME = env_first(
        'BUCKET',
        'AWS_STORAGE_BUCKET_NAME',
    )
    AWS_S3_REGION_NAME = env_first(
        'REGION',
        'AWS_S3_REGION_NAME',
        default='auto',
    )
    AWS_S3_ENDPOINT_URL = env_first(
        'ENDPOINT',
        'AWS_S3_ENDPOINT_URL',
        default=None,
    )
    AWS_S3_ADDRESSING_STYLE = env(
        'AWS_S3_ADDRESSING_STYLE',
        default='virtual',
    )
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_DEFAULT_ACL = 'private'
    AWS_QUERYSTRING_AUTH = True

    PRIVATE_MEDIA_LOCATION = 'private'
    PRIVATE_FILE_STORAGE = 'TheSum.storage_backends.PrivateMediaStorage'
else:
    MEDIA_URL = '/media/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'null': {
            'level': 'ERROR',
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        'django.security.DisallowedHost': {
            'handlers': ['null'],
            'propagate': False,
        },
    }
}

PROTOCOL = env('PROTOCOL', default='http')

LOGIN_URL = '/admin/login'

# Production security settings. These default to secure values only when ENV=PRODUCTION
# so local development remains simple.
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', default=IS_PRODUCTION)
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', default=IS_PRODUCTION)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', default=IS_PRODUCTION)
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=31536000 if IS_PRODUCTION else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=IS_PRODUCTION)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', default=False)
SECURE_CONTENT_TYPE_NOSNIFF = env_bool('SECURE_CONTENT_TYPE_NOSNIFF', default=True)
SECURE_BROWSER_XSS_FILTER = env_bool('SECURE_BROWSER_XSS_FILTER', default=True)
X_FRAME_OPTIONS = env('X_FRAME_OPTIONS', default='DENY')
SECURE_REFERRER_POLICY = env('SECURE_REFERRER_POLICY', default='same-origin')

if env_bool('USE_X_FORWARDED_PROTO', default=IS_PRODUCTION):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"
